### ISSUE TITLE
Embeddable Beispiel nicht konform zu IsyFact Detailkonzept Datenzugriff

### ISSUE THREAD

**Issue by aburghacc** [IsyFact/IsyFact-Vorlageanwendung#55]
Gemäß IsyFact Detailkonzept Komponente Datenzugriff implementieren Embeddable Datentypen die Methoden equals und hash unter Berücksichtigung aller Attribute. Zumindest im Beispiel https://github.com/IsyFact/IsyFact-Vorlageanwendung/blob/master/src/main/java/de/msg/terminfindung/persistence/entity/Organisator.java ist das nicht der Fall.
Das Detailkonzept verweist ausdrücklich auf die referenzierende Entitätsklasse.

**Comment by stdll** [comment]
Vielen Dank für das Issue! Die Abweichung wird im nächsten Release der IsyFact (1.8) behoben.
