### ISSUE TITLE
Layout: Weißer Balken auf der rechten Seite

### ISSUE THREAD

**Issue by stdll** [IsyFact/IsyFact-Vorlageanwendung#6]
### IST

Momentan wird ab einer bestimmten Bildschirmgröße ein weißer Streifen auf der rechten Seite des Layouts sichtbar.
### SOLL

Das Layout soll über die ganze Breite des Bildschirms gestreckt werden.

**Comment by vadimrichter** [comment]
Gelöst durch einführen der Regel in src/main/webapp/resources/css/style.css:
body{
    min-width: 100%;
    max-width: 100%;
}

Überschreibt die absolute Angabe in Pixel der min- und max-width.
